##     ##  #######  ######## #### ######## #### ######## ########
##     ## ##     ##    ##     ##  ##        ##  ##       ##     ##
##     ## ##     ##    ##     ##  ##        ##  ##       ##     ##
##     ## ##     ##    ##     ##  ######    ##  ######   ########
 ##   ##  ##     ##    ##     ##  ##        ##  ##       ##   ##
  ## ##   ##     ##    ##     ##  ##        ##  ##       ##    ##
   ###     #######     ##    #### ##       #### ######## ##     ##

name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: 1.9
authors: [blakeman8192, Kramer, ${project.author}]
website: ${project.website}
database: false
description: ${project.description}
depend: [Lib]

commands:
  fakevote:
    usage: /<command> <player> [service]
    description: Fake-votes for the player
    permission: votifier.fakevote

permissions:
  votifier.all:
    default: op
    description: Grants access to all votifier commands
    children:
      votifier.fakevote: true

  votifier.fakevote:
    default: false
    description: Allows access to /fakevote