##     ##  #######  ######## #### ######## #### ######## ########
##     ## ##     ##    ##     ##  ##        ##  ##       ##     ##
##     ## ##     ##    ##     ##  ##        ##  ##       ##     ##
##     ## ##     ##    ##     ##  ######    ##  ######   ########
 ##   ##  ##     ##    ##     ##  ##        ##  ##       ##   ##
  ## ##   ##     ##    ##     ##  ##        ##  ##       ##    ##
   ###     #######     ##    #### ##       #### ######## ##     ##

name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: 1.9
authors: [blakeman8192, Kramer, ${project.author}]
website: ${project.website}
database: false
description: ${project.description}
depend: [Lib, Data, LuckyScript]